### ISSUE TITLE
Extension manager shows error for Hanabi after reinstall

### ISSUE THREAD

**Issue by neuralnermal** [jeffshee/gnome-ext-hanabi#100]
Hanabi used to work on my laptop, but I deleted it due to battery issue. I wanted to give it a try again so I reinstalled it and now it is not working and Extension manager shows error below:

> SyntaxError: import declarations may only appear at top level of a module
>
>Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

Ubuntu 22.04.3 LTS, Gnome version 42.9, Wayland desktop

This could be unrelated, but when I installed Hanabi before, at first it showed wrong resolutions for animated wallpapers. Installing Clapper fixed it as it is recommended on the documentation file

**Comment by jeffshee** [comment]
Hi @neuralnermal,
Please take a look at the latest README. Recently I merged the GNOME 45 port into `master`, and since then installation for GNOME 44 and earlier has to use the `legacy` branch instead. The extensions for GNOME 45 are completely incompatible with the earlier version because of [the changes in the import system](https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/), and that's why we need a separate branch now.
- For GNOME 45
```
git clone https://github.com/jeffshee/gnome-ext-hanabi.git
```
- For GNOME 44 and earlier
```
git clone https://github.com/jeffshee/gnome-ext-hanabi.git -b legacy
```
