### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Seikm** [jeffshee/gnome-ext-hanabi#2]
![image](https://user-images.githubusercontent.com/37481700/178320463-48aebfd8-bee7-4c4e-858f-46450e038b9d.png)

[Video I'm using to test](https://www.pexels.com/video/changes-in-form-and-appearance-of-a-submerged-material-3163534/)

I did the complete download process, (in the download this appeared:  `meson.build:50: WARNING: The variable(s) 'settings_schema' in the input file 'metadata.json.in' are not present in the given configuration data.`)

I tried restarting the computer, leaving all other extensions disabled and it didn't work.

if this helps, I have an extension that shows applications minimized, and when I activate the Hanabi extension, a minimized application appears:
![image](https://user-images.githubusercontent.com/37481700/178321881-65c7a394-38db-44c2-b1a6-787888c22af7.png)
![image](https://user-images.githubusercontent.com/37481700/178322093-2b5d9fc0-1515-4030-87f6-95313e35ac77.png)
When I click to open, gnome topbar disappears and bugs

**Comment by CharmedGoose** [comment]
It doesn't work for me too

**Comment by jeffshee** [comment]
@Seikm Hi, thanks for reporting.

I just tested your video and it works on my system.
![image](https://user-images.githubusercontent.com/25530920/178459243-b982c844-25d4-4859-ba97-537055e8061a.png)

> I did the complete download process, (in the download this appeared: meson.build:50: WARNING: The variable(s) 'settings_schema' in the input file 'metadata.json.in' are not present in the given configuration data.)

This is actually fine. No problem.

> if this helps, I have an extension that shows applications minimized, and when I activate the Hanabi extension, a minimized application appears

That's Hanabi renderer. The extension works like this: 
1. A renderer (gtk4 app) that plays the video in fullscreen, minimized, and pager skipped so it doesn't show in your overview.
2. Extension part that gets what the renderer draws (window preview) and pastes it onto your Shell background.

Therefore, while Minimize Shelf shows the minimized renderer, you _shouldn't_ trigger it since it unhides the renderer.
(Yeah, I think we need a much better hiding mechanism 😛️)

Still, I have no idea why the video won't play on your system. The renderer should at least play the video. I need more information. Could you please provide the log file? You can see the output by executing the script `log.sh`. Also, a screen record would be nice if something failed but is hard to describe.

**Comment by Seikm** [comment]
@jeffshee Running `log.sh` and enabling the extension, these are the logs
![image](https://user-images.githubusercontent.com/37481700/178579685-e240e331-73cf-4f21-84be-f8d42926b351.png)

Additional Information:
I'm using two monitors
My video card is an NVIDIA RTX
and I downloaded my drivers (Geforce 700 series and later) from [this site](https://www.opensuse-community.org/)

**Comment by jeffshee** [comment]
From your log, it seems the renderer isn't working for some reason. It is
pretty hard to diagnose, as the only way to tweak the extension's behavior
is by modifying the code at the moment. Next time, I'll put more flags for
testing/debugging the extension. So for now, please wait for a few commits
more 😉

**Comment by Cry4775** [comment]
I've got the exact same problem as him. Log is the same too and i tried the test-renderer script and it showed a transparent window

**Comment by Seikm** [comment]
@Cry4775
I forgot to close the issue, my issue was resolved in [Issue #13](https://github.com/jeffshee/gnome-ext-hanabi/issues/13#issuecomment-1221552515).
You can test the `./test-renderer-sh` from [that post](https://github.com/jeffshee/gnome-ext-hanabi/issues/13#issuecomment-1221477492).
(Continue on [issue #13](https://github.com/jeffshee/gnome-ext-hanabi/issues/13), I will close this issue)
