### ISSUE TITLE
Wallpaper not appear on lockscreen

### ISSUE THREAD

**Issue by FuLygon** [jeffshee/gnome-ext-hanabi#36]
Enabling Hanabi Extension cause the lockscreen (not gdm) to be black (solid black color, can't change background even with [unlock background extension](https://extensions.gnome.org/extension/1476/unlock-dialog-background/))

I'm currently running Hanabi with `clappersink`, running on nvidia gpu (optimus-manager nvidia-only mode)

**Comment by AlynxZhou** [comment]
The reason is about racing condition:

1. This extension hooks `BackgroundManagers` to use its actors that display video players.
2. `UnlockDialog` creates its own `bgManagers` to add blur effects, and those managers uses this extensions actors because the hooks.
3. gnome-shell will disable all extensions when locking, so the video players are killed by the extensions.
4. Then the `unlockDialog` shows, but the actors has no video player, you got black.

A simple solution is not only call `Main.layoutManager._updateBackgrounds()`, but also call `Main.screenShield._dialog._updateBackgrounds()`, so after disabling this extension, `unlockDialog` got the normal backgrounds.

I just did and tested this on my branch, I'd like to send a PR after finished some other fix.
