### ISSUE TITLE
Extension does not work 

### ISSUE THREAD

**Issue by 3dw4rd-sn0wd3n** [jeffshee/gnome-ext-hanabi#61]
Extension does not work on my system

 - OS: Arch Linux x86_64
 - GNOME Shell: GNOME 44.1 
 - Session type: Wayland

My desktop just turned black after I enable extension, what should I do?
![image](https://user-images.githubusercontent.com/83455051/236913624-146f3094-5c61-4086-9357-c02746fbfc87.png)

**Comment by jeffshee** [comment]
@3dw4rd-sn0wd3n Hi,
Just to make sure, did you select the video to play in preference dialog after installing the extension? Is your system has the required multimedia codecs for video playback? You can check the video playback by using the same script that you used to install the extension. Execute `./run.sh renderer` and see if the video play without issue.

**Comment by jeffshee** [comment]
The error message you see might be related to a video file or codec issue. Have you tried playing a different video from a different source or in a different format to see if it works correctly?

**Comment by 3dw4rd-sn0wd3n** [comment]
> The error message you see might be related to a video file or codec issue. Have you tried playing a different video from a different source or in a different format to see if it works correctly?

i just tried to play video using forse gtkMediaFile and it worked

**Comment by 3dw4rd-sn0wd3n** [comment]
i've tried a couple of videos but it didn't work, but i didn't tried different video format

**Comment by jeffshee** [comment]
> i just tried to play video using force gtkMediaFile and it worked

Great to hear that! Just a heads up, using gtkMediaFile may result in sub-optimal performance (higher CPU usage). You could try converting the video to another format using `ffmpeg`, so you can avoid using that option. Also, if you don't mind, you could send me the video through Google Drive, so that I can investigate for a better solution.

**Comment by 3dw4rd-sn0wd3n** [comment]
> Also, if you don't mind, you could send me the video through Google Drive, so that I can investigate for a better solution.

https://drive.google.com/file/d/16kqSYpKwl9ucyjj492seluDIVb2rWRhq/view?usp=sharing

**Comment by 3dw4rd-sn0wd3n** [comment]
which video format is preferred for this extension?

**Comment by jeffshee** [comment]
Sorry for late reply.
> which video format is preferred for this extension?

Most video formats such as mp4 and webm should work without any issues. I tested your video on my system and it played successfully (on both `clappersink` and `gtkMediaFile`). I'm not sure why it isn't working on your system. Since it's not a video format issue, I guess there is something wrong with your multimedia codecs.

![Screenshot from 2023-05-13 19-32-15](https://github.com/jeffshee/gnome-ext-hanabi/assets/25530920/b7bd1769-c897-4509-b4cb-74048e2961c8)

**Comment by 3dw4rd-sn0wd3n** [comment]
It's finally worked, just changed video encoder to MPEG-4 in HandBrake and now it works through clappersink
![image](https://github.com/jeffshee/gnome-ext-hanabi/assets/83455051/b074d840-ea19-4906-8c8b-2274c27e6e38)

**Comment by jeffshee** [comment]
That's great! I'll mark this as solved then~
