### ISSUE TITLE
Steam buttons wont work

### ISSUE THREAD

**Issue by S1rPh0en1x** [jeffshee/gnome-ext-hanabi#7]
When I have activated the extension, a few steam buttons wont work.

And I found a "solution" that prevents freezing or a grey screen at startup, you can prevent it by closing the overview directly.
Extension which prevents overview at start-up: https://extensions.gnome.org/extension/4099/no-overview/

**Comment by jeffshee** [comment]
@S1rPh0en1x Hi, thanks for reporting. 

The steam button issue is fixed. 
![Screenshot from 2022-07-31 19-06-34](https://user-images.githubusercontent.com/25530920/182021419-66804af4-ebfc-4725-8739-c3955ec94752.png)

About the startup issue and the solution, since it is different from this issue, I'll create a new ticket and move that part over. 😄
