### ISSUE TITLE
Release in extensions.gnome.org

### ISSUE THREAD

**Issue by eruizc-dev** [jeffshee/gnome-ext-hanabi#74]
Are there any plans to publish this extension to <https://extensions.gnome.org>? Are there any limitations to do so?

It would be very convenient to install this extension from that website or the Extensions Manager app

**Comment by jeffshee** [comment]
Hi @eruizc-dev 

No, sadly. The reason is, it won't be any easier to install Hanabi from extension website since it has some dependencies that might not comes pre-installed with some distros. To provide easier installation, packages for  distros could be made in the future. I believe there is already a community AUR package available for Arch Linux. If you are using other distro, the installation script is probably your best bet, at least for now.

Thanks for question! Closed as answered. Please don't hesitate to ask if you have any other questions 😄

**Comment by eruizc-dev** [comment]
I'm currently using Fedora Silverblue which doesn't like installing things from scripts, and I guess the same would happen to other immutable distros like Nixos, and Vanilla OS

**Comment by jeffshee** [comment]
But the script installs everything to the user data directory (`~/.local/share`), not the system one. The website (extensions.gnome.org, aka EGO) does the same thing as well, so it shouldn't be a problem for immutable distros. 
Did you encounter any issues when installing this extension with Fedora Silverblue?

What if I published the extension to the EGO? If users install the extension from the EGO without having the necessary dependencies, things will break for them. They won't understand why things didn't work unless they visit the GitHub, read the README, install the dependencies, and then reinstall the extension. This process involves two steps and results in a bad user experience.

By choosing not to release the extension on the EGO, we can avoid these bad user experiences. This is because users, hopefully, will read the README and prepare everything necessary before installing the extension. I hope this explains my thought.

**Comment by eruizc-dev** [comment]
Oh yeah my bad, I made the mistake of not testing and assuming it would not work (as most installation scripts don't)

Thanks for clarifying
